### ISSUE TITLE
Add sequences support in table definition

### ISSUE THREAD

**Issue by euginio** [codenautas/backend-plus#104]
Agregar la posibilidad de marcar un campo de una tabla para que genere una sequencia en la db. Ya está funcionando.
Tareas pendientes:
1. Refactor discutido con Emilio en este commit: https://github.com/codenautas/backend-plus/commit/cefdd3ebbce056e436b91d313f62e99e8732ee2b

**Comment by euginio** [comment]
Implementación inicial en PR #105 luego hubo un refactor directamente sobre el master fuera del branch y PR. 
Todavía resta documentar la nueva funcionalidad

**Comment by manueldelapenna** [comment]
Si se cambia alguna especificación antes de cerrar el ticket por las dudas revisar tabla bitácora que usa secuencias. #49 (ubicada dentro de lib ya que es una tabla del framework)

**Comment by emilioplatzer** [comment]
Entiendo que esto anda. Revisen y cierren este issue si corresponde

**Comment by emilioplatzer** [comment]
No habiendo más comentarios lo cerramos porque la implementación está usándose hace tiempo
