### ISSUE TITLE
Al borrar un registro debe quitar los TR con details si los hay

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/backend-plus#120]
Ahora poniendo details (cuando la tabla detalle no tiene filas) te abre la tabla por si se quiere agregar un registro. Si se borra el registro de donde esta subtabla cuelga la subtabla se sigue viendo. 

Tiene que quitarse de la vista

**Comment by manueldelapenna** [comment]
aparentemente este problema es con la "edicion en forma de ficha" y pasa independientemente de la cantidad de registros
