### ISSUE TITLE
Al exportar en Excel respetar los números y fechas 

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/backend-plus#121]
Porque si no después no se puede operar con ellos. 

Para colmo la fecha se exporta en localeFormating

**Comment by manueldelapenna** [comment]
se acomoda exportador para que determine valores usando método toExcelValue de type-store [commit](https://github.com/codenautas/backend-plus/commit/1192def5f5db563949de905ca28032030a275a72)
