### ISSUE TITLE
fixedFields siempre vacío en myTables.js (sigba)

### ISSUE THREAD

**Issue by euginio** [codenautas/backend-plus#125]
En archivo myTables.js linea 1330 el atributo fixedFields siempre está vacío, lo cual hace que la condición del some se cumpla y nunca pase por el guardado

Como reproducirlo: En sigba agregando una nueva fila en la tabla valores, el campo cortes hace valida la condición del "some" que se describe mas arriba.

Tal vez sea mas correcto reportarlo en sigba y no aca.

**Comment by emilioplatzer** [comment]
Se arregló permitiendo filtra el null
