### ISSUE TITLE
Esquema para definir la tabla

### ISSUE THREAD

**Issue by ebtonini** [codenautas/backend-plus#144]
Poder agregar en qué esquema se va a generar la tabla que se define

**Comment by emilioplatzer** [comment]
Hecho en 74961018d022d369ddff6f53e0fce3ec3f9b875f

**Comment by emilioplatzer** [comment]
se pone en la definición de la tabla:

```ts
{ 
   name: "la_tabla",
   schema: "encu",
   ...
}
```
