### ISSUE TITLE
Agregar la barra laterial y superior en general para las aplicaciones

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/backend-plus#18]
De modo de poder colgar el menú principal, el logout, etc.

**Comment by emilioplatzer** [comment]
Incluso el reconect del #1 podría caer en la barra superior general.

**Comment by emilioplatzer** [comment]
Un ejemplo en: codenautas/pizarra

**Comment by emilioplatzer** [comment]
Quizás la barra lateral no sea necesaria (nadie la usa)

**Comment by estefi-capece** [comment]
Si agrego la línea `be.messages.connectedUser=username;` antes del done() después de haberse logueado (cuando pregunta a la base de datos por usuario y contraseña válida el login plus), así después se lo pasa al jade y en el jade agrego un span en la barra superior que diga "usuario:", sirve??

**Comment by emilioplatzer** [comment]
Agregado el menú superior (el lateral se desestima). En el commit 70280540332b09c0432db599acfd13d89668f19d se agrega también el menú a la barra superior.
