### ISSUE TITLE
Mostrar el nombre de usuario en la barra superior a la derecha

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/backend-plus#22]
Cuando esté #18

**Comment by estefi-capece** [comment]
Entiendo que ya está el #18.
Si agrego `be.messages.connectedUser=username` una vez que se logueó, entonces ya lo tengo como variable en el jade. Lo puedo agregar como un span en la barra superior. Serviría eso?

**Comment by emilioplatzer** [comment]
Hecho en varios (ej: 70280540332b09c0432db599acfd13d89668f19d)
