### ISSUE TITLE
Agregar automáticamente transacciones para los procedimientos

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/backend-plus#25]
Antes de ejecutarlo debe hacer `BEGIN TRANSACTION` y luego `COMMIT` o `ROLLBACK` según corresponda. 

Va dentro de `addProcedureServices` en backend-plus.js

**Comment by emilioplatzer** [comment]
Podés cambiar

return context.client.query("ROLLBACK").execute().then(function
(){context.client.done();},function(){throw err;});

Por

return context.client.query("ROLLBACK").execute().then(function(){
context.client.done(); },function(err2){     context.client.done();
Console.log ('black bla',err,'bla',err2);
throw err; });

Así siempre se hace el done. Y si hay doble error se loguea.

**Comment by estefi-capece** [comment]
Había hecho eso en un principio, pero tal vez sigo entendiendo mal cómo funciona. Puse: 
```
return context.client.query("ROLLBACK").execute().then(function(){
    context.client.done();},function(err2){
        context.client.done();
        console.log("Error in database when trying to "+procedureDef.action,err," Error trying to rollback ",err2);
        throw err;});
    }).then(function(result){

```

Pero eso hace que si hago cualquier cosa en la base de datos me tire el siguiente error cuando intento hacer borrar o agregar una fila en cualquier tabla:
```
ERROR Error: Bad return value in procedure. Undefined detected.
    at c:\hecho\npm\backend-plus\lib\backend-plus.js:426:31
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by emilioplatzer** [comment]
Hola

Lo que dice "Bad return value in procedure" lo puse yo para detectar
posibles omisiones nuestras mientras programamos. Eso ocurre cuando se
corta la cadena de promesas o cuando no se corta pero el último then no
tiene un return o si tiene un return el valor del return es undefined.
También puede significar que un catch no hace el correspondiente  throw
para propagar (patear el error) para máś afuera

[cambiando de tema, este teclado es un horror, o el gmail es una porqueríá
o no estáń bien integrados porque una vez que presiono el acento queda
trabado. Sigamos]

El problema debe estar (para esa versión en otro lado). Fijáte si quedó
algo más. En general:

   * cada bloque then (o sea la función que está dentro) tiene que tener un
return de un valor válido (y que esté en el scope o sea visible para el
return), salvo que se detecte un error en cuyo caso hay un  throw
   * cada bloque catch (o la segunda función que se le pasa como parámetro
al then) tiene que thener otro throw, en general de la misma variable err
que es parámetro de la función, salvo que haya doble error u otra cosa
rara. Si de ese error uno se puede recuperar y seguir en el camino normal
(por ejemplo si el error fue que se trató de abrir un archivo para
continuar escribiendo en él, pero si no estaba simplemente se creó uno
nuevo, se puede decir que uno se recuperó y puede seguir), entonces hay un
return.
  * Dentro de una función de un bloque catch o de un bloque then se pueden
llamar a funciones que devuelven promesas. En ese caso SIEMPRE hay que
encabezarlas con un return (porque si no se rompe la cadena de promesas y
eso se ejecuta en cualqueir orden, se crea un universo paralelo donde se
mueren gatitos y pitufos). Dentro de esa nueva cadena rigen las reglas de
rigor (o sea estas tres que estoy escribiendo ahora, y las que me estoy
olvidando de escribir).

Cuando vuelva buscamos ejemplos y escribimos una página en la wiki.

Beso


El 9 feb. 2017 10:58, "estefi-capece" <notifications@github.com> escribió:

Había hecho eso en un principio, pero tal vez sigo entendiendo mal cómo
funciona. Puse:

return context.client.query("ROLLBACK").execute().then(function(){
    context.client.done();},
function(err2){
        context.client.done();
        console.log("Error in database when trying to
"+procedureDef.action,err," Error trying to rollback ",err2);
        throw err;});
    }).then(function(result){


Pero eso hace que si hago cualquier cosa en la base de datos me tire el
siguiente error cuando intento hacer borrar o agregar una fila en cualquier
tabla:

ERROR Error: Bad return value in procedure. Undefined detected.
    at c:\hecho\npm\backend-plus\lib\backend-plus.js:426:31
    at process._tickCallback (internal/process/next_tick.js:103:7)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/codenautas/backend-plus/issues/25#issuecomment-278647738>,
or mute the thread
