### ISSUE TITLE
Agregar bitácora de procedimientos

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/backend-plus#49]

**Comment by emilioplatzer** [comment]
Un procedimiento está definido con `bitacora:{error:true, always:false, targetTable:null, targetPk}` 

Si `targetTable` está seteado, entonces no se hace el `insert` en bitácora y el `update` se hace en la tabla destino. `targetPk` tiene que existir y es la lista de los nombres de los parámetros que indican de dónde deducir la PK (que tiene que venir en los parámetros). 

Si `always` es true se inserta un registro en la tabla `bitacora` con: nombre del procedimiento, timestamp, parámetros, *datos de log de usuario* (de getContext() queremos username, machineId y navigator). Esta inserción se hace antes del "begin transaction". Si había `targetTable` en vez de insert se hace un update con el timestamp inicial y los *datos de log de usuario*.

Si `always` es false y `error` es true se hace el insert después del "commit" y solo en el caso de que se lanzó una excepción

Luego al terminar (y después del "commit") se hace un update poniendo el timestamp del final y el resultado (que puede ser lo que devolvió la función o un error) y el value que es false para error y true para ok.

**Comment by manueldelapenna** [comment]
Un procedimiento está definido con bitacora:{error:true, always:false, targetTable:null, targetTableBitacoraFields, targetTableUpdateFieldsCondition, }

Si targetTable está seteado, entonces se hace el insert en bitácora y ademas se hace update en la tabla destino. targetPk tiene que existir y es la lista de los nombres de los parámetros que indican de dónde deducir la PK (que tiene que venir en los parámetros).

Si always es true se inserta un registro en la tabla bitacora con: nombre del procedimiento, timestamp, parámetros, datos de log de usuario (de getContext() queremos username, machineId y navigator). Esta inserción se hace antes del "begin transaction". Si había targetTable en vez de insert se hace un update con el timestamp inicial y los datos de log de usuario.

Si always es false y error es true se hace el insert después del "commit" y solo en el caso de que se lanzó una excepción

Luego al terminar (y después del "commit") se hace un update poniendo el timestamp del final y el resultado (que puede ser lo que devolvió la función o un error) y el value que es false para error y true para ok. Si se setea target table se hace lo mismo en esa tabla
