### ISSUE TITLE
Error: EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by estefi-capece** [codenautas/backend-plus#65]
En el módulo "write-file-atomic", la función _writeFile toma el filename y le calcula var tmpfile = getTmpname(filename). 
La variable resulta: tempfile=l3tvCt6WNn4l3In8IDkoMH912ifsepRk.json.239390485

getTmpname() le agrega el .239390485, y por algún motivo no le deja escribir el archivo con ese nombre

**Comment by emilioplatzer** [comment]
Aparentemente solo pasa en windows.

**Comment by emilioplatzer** [comment]
Se arregló separando las sessions.

**Comment by emilioplatzer** [comment]
Si vemos que se vuelve a mezclar (con distintos ports) hay que incluir el port o el nombre de la aplicación o el número de instalación en el nombre del connect.sid
