### ISSUE TITLE
Alineación de los números

### ISSUE THREAD

**Issue by estefi-capece** [codenautas/backend-plus#67]
Los números en las tablas aparecen con alineación izquierda. Pasarlos a la derecha

**Comment by estefi-capece** [comment]
Para cambiar la alineación se le podría dar clase number a los td que tengan números con algo así:
Donde se le da el valor que aparece en el td:
```
td.setTypedValue(depot.row[fieldDef.name]);
```
Agregar abajo: 

```
if(typeof depot.row[fieldDef.name]==="number"){
     td.setAttribute("class","number");                    
}
```

**Comment by emilioplatzer** [comment]
Listo. Ahora hay un attributo type-align que se completa con los datos de align de type-store
