### ISSUE TITLE
bigint no funciona bien

### ISSUE THREAD

**Issue by estefi-capece** [codenautas/backend-plus#71]
Cuando entra en la tabla bigint que tenga la menos una fila muestra el error: `Not a Number in input is object`. Para reproducir el error:
* Entrar en la tabla, agregar una fila completa, graba todos los campos (los muestra en verde)
* Salir de la tabla
* Volver a entrar

Se muestra el error. En la base de datos graba bien, pero no los puede mostrar en pantalla.

**Comment by estefi-capece** [comment]
Este issue se arregla si en my-things, en la función `adaptData ` se le agrega en el primer `if`:
 || fieldDef.typeName==='bigint'

**Comment by emilioplatzer** [comment]
Hola

¡Tengo teclado! Escribo con el teléfono pero tengo teclado. Vamos a ver si
puedo ser más explícito.

Creo que sí que se puede arreglar como decís. Pero agregále un //TODO
mejorar esto del bigint

Cuando vuelva hacéme acordar de eso y lo vamos pasando bien al type-store.
Te digo cuáles son los criterios así después lo podés hacer sola.

Besos

**Comment by emilioplatzer** [comment]
Verificar nuevamente. Creo que se solucionó
