### ISSUE TITLE
Definir cómo mostrar grillas aumentadas con campos del "resto"

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/backend-plus#99]
Para #97

**Comment by manueldelapenna** [comment]
1) El importador guarda en un campo text un JSON con los campos extra al importar archivo
2) Se puede mostrar u ocultar el JSON en la grilla (se muestra como texto, que es el tipo del campo, lo ideal es ocultarlo, ya que si se quiere filtrar convendría definirlo como un campo más)
3) El exportador toma el JSON y genera el archivo agregando las columnas guardadas en el campo
